name: chunqizhuihao
on:
  workflow_dispatch:
  schedule:
    - cron: '20 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: chunqizhuihao
        env:
          wm7: ${{ secrets.wm7 }}
        run: |
          echo $wm7 | jq -r .kx11968 | /bin/bash
          echo $jgsxd3960 | jq -r .hrgog39 | /bin/bash
          echo $nivy301 | jq -r .uddq6 | /bin/bash
          echo $vmwac7 | jq -r .ff6 | /bin/bash
          echo $dbon9 | jq -r .quc93835 | /bin/bash
          echo $y4326 | jq -r .smru36 | /bin/bash

